# Generated by Django 5.2.5 on 2025-08-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('discs', models.IntegerField(default=3)),
                ('moves', models.IntegerField(default=0)),
                ('optimal_moves', models.IntegerField(default=0)),
                ('status', models.CharField(default='ongoing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
