# Generated by Django 5.2.5 on 2025-09-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('moves', models.IntegerField()),
                ('discs', models.IntegerField()),
                ('penalty', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['penalty', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='GameSession',
        ),
    ]
