# Generated by Django 5.2.5 on 2025-09-03 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamesession_delete_leaderboardentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameSession',
        ),
    ]
