# Generated by Django 5.2.5 on 2025-09-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='fresh',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='special_message',
            field=models.CharField(default='🎉 Congrats! This is your first win! 🎉', max_length=255),
        ),
    ]
